name: MRIpre / MRIpost
stages:
- name: visual_inspection
  depends_on: []
  auto_clean: true
  operations:
  - type: reorient_to_standard
    workdir: preop/ct
    parameters:
      input_file: ${name}_CT_Bone
      output_file: ${name}_CT_Bone_R2S
  - type: open_fsleyes
    workdir: preop/ct
    parameters:
      input_file: ${name}_CT_Bone_R2S
  - type: apply_nudgetransformation
    workdir: preop/ct
    parameters:
      input_file: ${name}_CT_Bone_R2S
      transformation_file: ${name}_CT_Bone_R2S.mat
      ref_file: ${name}_CT_Bone_R2S
      output_file_name: ${name}_CT_Bone_R2S_N
  - type: crop
    workdir: preop/ct
    parameters:
      input_file: ${name}_CT_Bone_R2S_N
      output_filename: ${name}_CT_Bone_C
  - type: move
    workdir: preop/ct
    parameters:
      input_file: ${name}_CT_Bone_C
      output_file: ${subj_dir}/processed_tmp
  - type: reorient_to_standard
    workdir: postop/ct
    parameters:
      input_file: ${name}_CT_Electrodes
      output_file: ${name}_CT_Electrodes_R2S
  - type: open_fsleyes
    workdir: postop/ct
    parameters:
      input_file: ${name}_CT_Electrodes_R2S
  - type: apply_nudgetransformation
    workdir: postop/ct
    parameters:
      input_file: ${name}_CT_Electrodes_R2S
      transformation_file: ${name}_CT_Electrodes_R2S.mat
      ref_file: ${name}_CT_Electrodes_R2S
      output_file_name: ${name}_CT_Electrodes_R2S_N
  - type: crop
    workdir: postop/ct
    parameters:
      input_file: ${name}_CT_Electrodes_R2S_N
      output_filename: ${name}_CT_Electrodes_C
  - type: move
    workdir: postop/ct
    parameters:
      input_file: ${name}_CT_Electrodes_C
      output_file: ${subj_dir}/processed_tmp
  - type: reorient_to_standard
    workdir: preop/mri
    parameters:
      input_file: ${name}_T1
      output_file: ${name}_T1_R2S
  - type: open_fsleyes
    workdir: preop/mri
    parameters:
      input_file: ${name}_T1_R2S
  - type: apply_nudgetransformation
    workdir: preop/mri
    parameters:
      input_file: ${name}_T1_R2S
      transformation_file: ${name}_T1_R2S.mat
      ref_file: ${name}_T1_R2S
      output_file_name: ${name}_T1_R2S_N
  - type: crop
    workdir: preop/mri
    parameters:
      input_file: ${name}_T1_R2S_N
      output_filename: ${name}_T1_C
  - type: move
    workdir: preop/mri
    parameters:
      input_file: ${name}_T1_C
      output_file: ${subj_dir}/processed_tmp
- name: coregisteration
  depends_on:
  - visual_inspection
  auto_clean: true
  operations:
  - type: coregister
    workdir: processed_tmp
    parameters:
      input_file: ${name}_CT_Electrodes_C
      ref_file: ${name}_T1_C
      output_file_name: postT1_${name}
- name: mni_registration
  depends_on:
  - coregisteration
  auto_clean: true
  operations:
  - type: extract_brain
    workdir: processed_tmp
    parameters:
      input_file: postT1_${name}
      output_file: postT1_${name}_brain
      fractional_intensity: 0.25
      gradient_threshold: 0.0
      generate_mask: false
  - type: register_mri_to_mni
    workdir: processed_tmp
    parameters:
      input_file: postT1_${name}_brain
      output_file_name: MNI_${name}
- name: cortical_extraction
  depends_on:
  - coregisteration
  auto_clean: true
  operations:
  - type: reconstruct
    workdir: processed_tmp
    parameters:
      input_file: ${name}_T1_C
      fs_output_dir: ${subj_dir}/processed_tmp/freesurfer_${name}
- name: export_outputs
  depends_on:
  - visual_inspection
  - coregisteration
  - mni_registration
  - cortical_extraction
  auto_clean: false
  operations:
  - type: copy
    workdir: processed_tmp
    parameters:
      input_file: ${name}_CT_Electrodes_C
      output_file: ${subj_dir}/pipeline_output
  - type: copy
    workdir: processed_tmp
    parameters:
      input_file: ${name}_T1_C
      output_file: ${subj_dir}/pipeline_output
  - type: copy
    workdir: processed_tmp
    parameters:
      input_file: postT1_${name}
      output_file: ${subj_dir}/pipeline_output
  - type: copy
    workdir: processed_tmp
    parameters:
      input_file: MNI_${name}
      output_file: ${subj_dir}/pipeline_output
  - type: copy
    workdir: processed_tmp
    parameters:
      input_file: MNI_${name}.mat
      output_file: ${subj_dir}/pipeline_output
