# Define stage outputs and dependencies for automatic cleaning
stage_outputs:
  preprocessing:
    - "*_C.nii*"          # Cropped images
    - "*_C"               # Cropped directories
  coregisteration: 
    - "*.mat"             # Transformation matrices
    - "v_*"               # Registration outputs
    - "b_*"               # Registration outputs
  extract_electrodes:
    - "r_*"               # Applied transformation outputs
    - "*_seeg*"           # SEEG outputs
    - "*_sub*"            # Subtraction outputs
  apply_mask:
    - "*_stripped*"       # Brain extraction outputs
    - "*_masked*"         # Masked outputs
  mni_registration:
    - "MNI_*"             # MNI registration outputs
    - "*_rigid*"          # Rigid registration temp files
    - "norm_*"            # Normalized images
    - "*_ref_brain*"      # Brain-extracted reference images
    - "*_brain.mat"       # Brain registration matrices
  cortical_extraction:
    - "freesurfer_*"      # FreeSurfer outputs

stages:
  - name: preprocessing
    auto_clean: true
    operations:
      - type: open_fsleyes
        workdir: preop/ct
        files: ["${name}_CT_Bone"]
      - type: crop
        workdir: preop/ct
        files: ["${name}_CT_Bone", "${name}_CT_Bone_C"]
      - type: move
        workdir: preop/ct
        files: ["${name}_CT_Bone_C", "${subj_dir}/processed_tmp"]
      - type: open_fsleyes
        workdir: preop/ct
        files: ["${name}_CT_Electrodes"]
      - type: crop
        workdir: postop/ct
        files: ["${name}_CT_Electrodes", "${name}_CT_Electrodes_C"]
      - type: move
        workdir: postop/ct
        files: ["${name}_CT_Electrodes_C", "${subj_dir}/processed_tmp"]
      - type: open_fsleyes
        workdir: preop/mri
        files: ["${name}_T1"]
      - type: crop
        workdir: preop/mri
        files: ["${name}_T1", "${name}_T1_C"]
      - type: move
        workdir: preop/mri
        files: ["${name}_T1_C", "${subj_dir}/processed_tmp"]

  - name: coregisteration
    auto_clean: true
    operations:
      - type: coregister
        workdir: processed_tmp
        files: ["${name}_CT_Bone_C", "${name}_CT_Electrodes_C", "v_${name}_bone_mask"]
      - type: coregister
        workdir: processed_tmp
        files: ["${name}_T1_C", "${name}_CT_Electrodes_C", "v_${name}_ref"]
      - type: coregister
        workdir: processed_tmp
        files: ["${name}_CT_Electrodes_C", "${name}_CT_Bone_C", "b_${name}_postimplant_ct"]

  - name: extract_electrodes
    auto_clean: true
    operations:
      - type: subtract
        workdir: processed_tmp
        files: ["b_${name}_postimplant_ct", "${name}_CT_Bone_C", "b_${name}_postimplant_ct_sub"]
      - type: threshold
        workdir: processed_tmp
        files: ["b_${name}_postimplant_ct_sub", "b_${name}_seeg"]
      - type: apply_transformation
        workdir: processed_tmp
        files: ["b_${name}_seeg", "v_${name}_bone_mask.mat", "${name}_CT_Electrodes_C", "r_${name}_seeg"]

  - name: apply_mask
    auto_clean: true
    operations:
      - type: extract_brain
        workdir: processed_tmp
        files: ["v_${name}_bone_mask", "${name}_stripped"]
      - type: mask
        workdir: processed_tmp
        files: ["r_${name}_seeg", "${name}_stripped_mask", "r_${name}_seeg_masked"]

  - name: mni_registration
    auto_clean: true
    operations:
      - type: extract_brain2
        workdir: processed_tmp
        files: ["v_${name}_ref", "v_${name}_ref_brain"]
      - type: register_mri_to_mni
        workdir: processed_tmp
        files: ["v_${name}_ref_brain", "MNI_${name}_ref_brain"]

  - name: cortical_extraction
    auto_clean: true
    operations:
      - type: reconstruct
        workdir: processed_tmp
        files: ["v_${name}_ref", "${subj_dir}/processed_tmp/freesurfer_${name}"]
