# Form implementation generated from reading ui file 'ciclone/forms/AboutDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(400, 300)
        AboutDialog.setModal(True)
        AboutDialog.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appNameLabel = QtWidgets.QLabel(parent=AboutDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.appNameLabel.setFont(font)
        self.appNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.appNameLabel.setObjectName("appNameLabel")
        self.verticalLayout.addWidget(self.appNameLabel)
        self.versionLabel = QtWidgets.QLabel(parent=AboutDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.versionLabel.setFont(font)
        self.versionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.versionLabel.setObjectName("versionLabel")
        self.verticalLayout.addWidget(self.versionLabel)
        self.descriptionLabel = QtWidgets.QLabel(parent=AboutDialog)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout.addWidget(self.descriptionLabel)
        self.copyrightLabel = QtWidgets.QLabel(parent=AboutDialog)
        self.copyrightLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.verticalLayout.addWidget(self.copyrightLabel)
        self.authorLabel = QtWidgets.QLabel(parent=AboutDialog)
        self.authorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.authorLabel.setWordWrap(True)
        self.authorLabel.setObjectName("authorLabel")
        self.verticalLayout.addWidget(self.authorLabel)
        self.licenseLabel = QtWidgets.QLabel(parent=AboutDialog)
        self.licenseLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.licenseLabel.setObjectName("licenseLabel")
        self.verticalLayout.addWidget(self.licenseLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AboutDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AboutDialog)
        self.buttonBox.accepted.connect(AboutDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About CiCLONE"))
        self.appNameLabel.setText(_translate("AboutDialog", "CiCLONE"))
        self.versionLabel.setText(_translate("AboutDialog", "Version X.X.X"))
        self.descriptionLabel.setText(_translate("AboutDialog", "Application Description"))
        self.copyrightLabel.setText(_translate("AboutDialog", "Copyright Information"))
        self.authorLabel.setText(_translate("AboutDialog", "Author: Name"))
        self.licenseLabel.setText(_translate("AboutDialog", "Licensed under License"))
