# Form implementation generated from reading ui file 'ciclone/forms/ImagesViewer.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImagesViewer(object):
    def setupUi(self, ImagesViewer):
        ImagesViewer.setObjectName("ImagesViewer")
        ImagesViewer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=ImagesViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.Axial_verticalLayout = QtWidgets.QVBoxLayout()
        self.Axial_verticalLayout.setObjectName("Axial_verticalLayout")
        self.Axial_horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Axial_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.Axial_horizontalSlider.setSizePolicy(sizePolicy)
        self.Axial_horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Axial_horizontalSlider.setObjectName("Axial_horizontalSlider")
        self.Axial_verticalLayout.addWidget(self.Axial_horizontalSlider)
        self.Axial_ImagePreview = QtWidgets.QLabel(parent=self.centralwidget)
        self.Axial_ImagePreview.setText("")
        self.Axial_ImagePreview.setObjectName("Axial_ImagePreview")
        self.Axial_verticalLayout.addWidget(self.Axial_ImagePreview)
        self.gridLayout.addLayout(self.Axial_verticalLayout, 0, 0, 1, 1)
        self.Coronal_verticalLayout = QtWidgets.QVBoxLayout()
        self.Coronal_verticalLayout.setObjectName("Coronal_verticalLayout")
        self.Coronal_horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Coronal_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.Coronal_horizontalSlider.setSizePolicy(sizePolicy)
        self.Coronal_horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Coronal_horizontalSlider.setObjectName("Coronal_horizontalSlider")
        self.Coronal_verticalLayout.addWidget(self.Coronal_horizontalSlider)
        self.Coronal_ImagePreview = QtWidgets.QLabel(parent=self.centralwidget)
        self.Coronal_ImagePreview.setText("")
        self.Coronal_ImagePreview.setObjectName("Coronal_ImagePreview")
        self.Coronal_verticalLayout.addWidget(self.Coronal_ImagePreview)
        self.gridLayout.addLayout(self.Coronal_verticalLayout, 0, 1, 1, 1)
        self.Fillerl_ImagePreview = QtWidgets.QLabel(parent=self.centralwidget)
        self.Fillerl_ImagePreview.setText("")
        self.Fillerl_ImagePreview.setObjectName("Fillerl_ImagePreview")
        self.gridLayout.addWidget(self.Fillerl_ImagePreview, 1, 0, 1, 1)
        self.Sagittal_verticalLayout = QtWidgets.QVBoxLayout()
        self.Sagittal_verticalLayout.setObjectName("Sagittal_verticalLayout")
        self.Sagittal_horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sagittal_horizontalSlider.sizePolicy().hasHeightForWidth())
        self.Sagittal_horizontalSlider.setSizePolicy(sizePolicy)
        self.Sagittal_horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Sagittal_horizontalSlider.setObjectName("Sagittal_horizontalSlider")
        self.Sagittal_verticalLayout.addWidget(self.Sagittal_horizontalSlider)
        self.Sagittal_ImagePreview = QtWidgets.QLabel(parent=self.centralwidget)
        self.Sagittal_ImagePreview.setText("")
        self.Sagittal_ImagePreview.setObjectName("Sagittal_ImagePreview")
        self.Sagittal_verticalLayout.addWidget(self.Sagittal_ImagePreview)
        self.gridLayout.addLayout(self.Sagittal_verticalLayout, 1, 1, 1, 1)
        ImagesViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ImagesViewer)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        ImagesViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ImagesViewer)
        self.statusbar.setObjectName("statusbar")
        ImagesViewer.setStatusBar(self.statusbar)

        self.retranslateUi(ImagesViewer)
        QtCore.QMetaObject.connectSlotsByName(ImagesViewer)

    def retranslateUi(self, ImagesViewer):
        _translate = QtCore.QCoreApplication.translate
        ImagesViewer.setWindowTitle(_translate("ImagesViewer", "ImagesViewer"))
