# Form implementation generated from reading ui file 'ciclone/forms/Viewer3D.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Viewer3D(object):
    def setupUi(self, Viewer3D):
        Viewer3D.setObjectName("Viewer3D")
        Viewer3D.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Viewer3D)
        self.gridLayout.setObjectName("gridLayout")
        self.Preview3D = QtWidgets.QWidget(parent=Viewer3D)
        self.Preview3D.setObjectName("Preview3D")
        self.gridLayout.addWidget(self.Preview3D, 0, 0, 1, 1)

        self.retranslateUi(Viewer3D)
        QtCore.QMetaObject.connectSlotsByName(Viewer3D)

    def retranslateUi(self, Viewer3D):
        _translate = QtCore.QCoreApplication.translate
        Viewer3D.setWindowTitle(_translate("Viewer3D", "3D Viewer"))
